### ISSUE TITLE
Add init template

### ISSUE THREAD

**Issue by sonelu** [sonelu/roboglia#35]
Add an "init template" that can be defined at the top of the robot independent on device and then applied in the ``init`` attribute of the device without having to repeat all the init values.

ex:

```
inits:
  default:
    return_delay_time: 0
    cw_angle_limit: 0
    ccw_angle_limit: 0
    control_mode: 2
    ...

devices:
  d11:
     ...
     init:
       template: default
       <other reg>: <value>

...

```
